// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: rpc/backstage.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PeoRequest) Reset() {
	*x = PeoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_backstage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeoRequest) ProtoMessage() {}

func (x *PeoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_backstage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeoRequest.ProtoReflect.Descriptor instead.
func (*PeoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_backstage_proto_rawDescGZIP(), []int{0}
}

type PeoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg    string  `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Time   []int64 `protobuf:"varint,3,rep,packed,name=Time,proto3" json:"Time,omitempty"`
	People []int64 `protobuf:"varint,4,rep,packed,name=People,proto3" json:"People,omitempty"`
}

func (x *PeoResponse) Reset() {
	*x = PeoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_backstage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeoResponse) ProtoMessage() {}

func (x *PeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_backstage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeoResponse.ProtoReflect.Descriptor instead.
func (*PeoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_backstage_proto_rawDescGZIP(), []int{1}
}

func (x *PeoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PeoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PeoResponse) GetTime() []int64 {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *PeoResponse) GetPeople() []int64 {
	if x != nil {
		return x.People
	}
	return nil
}

type JobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_backstage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_backstage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_rpc_backstage_proto_rawDescGZIP(), []int{2}
}

type JobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg    string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Job    []string `protobuf:"bytes,3,rep,name=Job,proto3" json:"Job,omitempty"`
	People []int64  `protobuf:"varint,4,rep,packed,name=People,proto3" json:"People,omitempty"`
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_backstage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_backstage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_rpc_backstage_proto_rawDescGZIP(), []int{3}
}

func (x *JobResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JobResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *JobResponse) GetJob() []string {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobResponse) GetPeople() []int64 {
	if x != nil {
		return x.People
	}
	return nil
}

var File_rpc_backstage_proto protoreflect.FileDescriptor

var file_rpc_backstage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x0c, 0x0a, 0x0a, 0x50, 0x65,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x0b, 0x50, 0x65, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x0b, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x4a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06,
	0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x32, 0x68, 0x0a, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x32, 0x34, 0x70, 0x12, 0x0f, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x4a, 0x6f, 0x62, 0x12, 0x0f, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rpc_backstage_proto_rawDescOnce sync.Once
	file_rpc_backstage_proto_rawDescData = file_rpc_backstage_proto_rawDesc
)

func file_rpc_backstage_proto_rawDescGZIP() []byte {
	file_rpc_backstage_proto_rawDescOnce.Do(func() {
		file_rpc_backstage_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_backstage_proto_rawDescData)
	})
	return file_rpc_backstage_proto_rawDescData
}

var file_rpc_backstage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_backstage_proto_goTypes = []interface{}{
	(*PeoRequest)(nil),  // 0: rpc.PeoRequest
	(*PeoResponse)(nil), // 1: rpc.PeoResponse
	(*JobRequest)(nil),  // 2: rpc.JobRequest
	(*JobResponse)(nil), // 3: rpc.JobResponse
}
var file_rpc_backstage_proto_depIdxs = []int32{
	0, // 0: rpc.backstage.Get24p:input_type -> rpc.PeoRequest
	2, // 1: rpc.backstage.GetSeaJob:input_type -> rpc.JobRequest
	1, // 2: rpc.backstage.Get24p:output_type -> rpc.PeoResponse
	3, // 3: rpc.backstage.GetSeaJob:output_type -> rpc.JobResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_backstage_proto_init() }
func file_rpc_backstage_proto_init() {
	if File_rpc_backstage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_backstage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_backstage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_backstage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_backstage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_backstage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_backstage_proto_goTypes,
		DependencyIndexes: file_rpc_backstage_proto_depIdxs,
		MessageInfos:      file_rpc_backstage_proto_msgTypes,
	}.Build()
	File_rpc_backstage_proto = out.File
	file_rpc_backstage_proto_rawDesc = nil
	file_rpc_backstage_proto_goTypes = nil
	file_rpc_backstage_proto_depIdxs = nil
}
