// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: rpc/article.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextID   int64 `protobuf:"varint,1,opt,name=NextID,proto3" json:"NextID,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *ArtsRequest) Reset() {
	*x = ArtsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtsRequest) ProtoMessage() {}

func (x *ArtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtsRequest.ProtoReflect.Descriptor instead.
func (*ArtsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{0}
}

func (x *ArtsRequest) GetNextID() int64 {
	if x != nil {
		return x.NextID
	}
	return 0
}

func (x *ArtsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type Art struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid    int64  `protobuf:"varint,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Info    string `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	Tag     string `protobuf:"bytes,5,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Time    int64  `protobuf:"varint,6,opt,name=Time,proto3" json:"Time,omitempty"`
	LikeSum int64  `protobuf:"varint,7,opt,name=LikeSum,proto3" json:"LikeSum,omitempty"`
}

func (x *Art) Reset() {
	*x = Art{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Art) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Art) ProtoMessage() {}

func (x *Art) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Art.ProtoReflect.Descriptor instead.
func (*Art) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{1}
}

func (x *Art) GetUuid() int64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *Art) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Art) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Art) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Art) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Art) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Art) GetLikeSum() int64 {
	if x != nil {
		return x.LikeSum
	}
	return 0
}

type ArtsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Date []*Art `protobuf:"bytes,2,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *ArtsResponse) Reset() {
	*x = ArtsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtsResponse) ProtoMessage() {}

func (x *ArtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtsResponse.ProtoReflect.Descriptor instead.
func (*ArtsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{2}
}

func (x *ArtsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ArtsResponse) GetDate() []*Art {
	if x != nil {
		return x.Date
	}
	return nil
}

type ArtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ArtRequest) Reset() {
	*x = ArtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtRequest) ProtoMessage() {}

func (x *ArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtRequest.ProtoReflect.Descriptor instead.
func (*ArtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{3}
}

func (x *ArtRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ArtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msq  string `protobuf:"bytes,2,opt,name=Msq,proto3" json:"Msq,omitempty"`
	Date []*Art `protobuf:"bytes,3,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *ArtResponse) Reset() {
	*x = ArtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtResponse) ProtoMessage() {}

func (x *ArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtResponse.ProtoReflect.Descriptor instead.
func (*ArtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{4}
}

func (x *ArtResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ArtResponse) GetMsq() string {
	if x != nil {
		return x.Msq
	}
	return ""
}

func (x *ArtResponse) GetDate() []*Art {
	if x != nil {
		return x.Date
	}
	return nil
}

type AddArtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=UderId,proto3" json:"UderId,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Info   string `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	Tag    string `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Time   int64  `protobuf:"varint,5,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *AddArtRequest) Reset() {
	*x = AddArtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtRequest) ProtoMessage() {}

func (x *AddArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtRequest.ProtoReflect.Descriptor instead.
func (*AddArtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{5}
}

func (x *AddArtRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddArtRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddArtRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *AddArtRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AddArtRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type AddArtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msq  string `protobuf:"bytes,2,opt,name=Msq,proto3" json:"Msq,omitempty"`
}

func (x *AddArtResponse) Reset() {
	*x = AddArtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArtResponse) ProtoMessage() {}

func (x *AddArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArtResponse.ProtoReflect.Descriptor instead.
func (*AddArtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{6}
}

func (x *AddArtResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddArtResponse) GetMsq() string {
	if x != nil {
		return x.Msq
	}
	return ""
}

type MyArtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtId int64 `protobuf:"varint,1,opt,name=ArtId,proto3" json:"ArtId,omitempty"`
}

func (x *MyArtRequest) Reset() {
	*x = MyArtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyArtRequest) ProtoMessage() {}

func (x *MyArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyArtRequest.ProtoReflect.Descriptor instead.
func (*MyArtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{7}
}

func (x *MyArtRequest) GetArtId() int64 {
	if x != nil {
		return x.ArtId
	}
	return 0
}

type MyArtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msq  string `protobuf:"bytes,2,opt,name=Msq,proto3" json:"Msq,omitempty"`
	Date []*Art `protobuf:"bytes,3,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *MyArtResponse) Reset() {
	*x = MyArtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyArtResponse) ProtoMessage() {}

func (x *MyArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyArtResponse.ProtoReflect.Descriptor instead.
func (*MyArtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{8}
}

func (x *MyArtResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MyArtResponse) GetMsq() string {
	if x != nil {
		return x.Msq
	}
	return ""
}

func (x *MyArtResponse) GetDate() []*Art {
	if x != nil {
		return x.Date
	}
	return nil
}

type UpdateArtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtId int64  `protobuf:"varint,1,opt,name=ArtId,proto3" json:"ArtId,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Info  string `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	Tag   string `protobuf:"bytes,4,opt,name=Tag,proto3" json:"Tag,omitempty"`
	Time  int64  `protobuf:"varint,5,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *UpdateArtRequest) Reset() {
	*x = UpdateArtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtRequest) ProtoMessage() {}

func (x *UpdateArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateArtRequest) GetArtId() int64 {
	if x != nil {
		return x.ArtId
	}
	return 0
}

func (x *UpdateArtRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateArtRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *UpdateArtRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UpdateArtRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type UpdateArtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msq  string `protobuf:"bytes,2,opt,name=Msq,proto3" json:"Msq,omitempty"`
	Date *Art   `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *UpdateArtResponse) Reset() {
	*x = UpdateArtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtResponse) ProtoMessage() {}

func (x *UpdateArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtResponse.ProtoReflect.Descriptor instead.
func (*UpdateArtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateArtResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateArtResponse) GetMsq() string {
	if x != nil {
		return x.Msq
	}
	return ""
}

func (x *UpdateArtResponse) GetDate() *Art {
	if x != nil {
		return x.Date
	}
	return nil
}

type DelArtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Art int64 `protobuf:"varint,1,opt,name=Art,proto3" json:"Art,omitempty"`
}

func (x *DelArtRequest) Reset() {
	*x = DelArtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArtRequest) ProtoMessage() {}

func (x *DelArtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArtRequest.ProtoReflect.Descriptor instead.
func (*DelArtRequest) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{11}
}

func (x *DelArtRequest) GetArt() int64 {
	if x != nil {
		return x.Art
	}
	return 0
}

type DelArtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msq  string `protobuf:"bytes,2,opt,name=Msq,proto3" json:"Msq,omitempty"`
	Date []*Art `protobuf:"bytes,3,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *DelArtResponse) Reset() {
	*x = DelArtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_article_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArtResponse) ProtoMessage() {}

func (x *DelArtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_article_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArtResponse.ProtoReflect.Descriptor instead.
func (*DelArtResponse) Descriptor() ([]byte, []int) {
	return file_rpc_article_proto_rawDescGZIP(), []int{12}
}

func (x *DelArtResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DelArtResponse) GetMsq() string {
	if x != nil {
		return x.Msq
	}
	return ""
}

func (x *DelArtResponse) GetDate() []*Art {
	if x != nil {
		return x.Date
	}
	return nil
}

var File_rpc_article_proto protoreflect.FileDescriptor

var file_rpc_article_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x41, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x65, 0x78, 0x74, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x65, 0x78, 0x74, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x03,
	0x41, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x4c, 0x69, 0x6b, 0x65, 0x53, 0x75, 0x6d, 0x22, 0x40, 0x0a, 0x0c, 0x41, 0x72, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x72, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x41, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x51, 0x0a, 0x0b, 0x41,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x73, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x71,
	0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x75,
	0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x55, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61,
	0x67, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x36, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x71, 0x22, 0x24, 0x0a,
	0x0c, 0x4d, 0x79, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x41, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x72,
	0x74, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x0d, 0x4d, 0x79, 0x41, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x71, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41,
	0x72, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x76, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x41, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x41, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x57, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x71,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x41, 0x72, 0x74, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x41, 0x72, 0x74, 0x22, 0x54, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x4d, 0x73, 0x71, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x65, 0x32, 0xcc, 0x02, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x2f,
	0x0a, 0x08, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x72, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x41, 0x72, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2c, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x41, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a,
	0x0c, 0x41, 0x64, 0x64, 0x4d, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x12, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x4d, 0x79, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x79, 0x41, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x79, 0x41,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x65,
	0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x41, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_article_proto_rawDescOnce sync.Once
	file_rpc_article_proto_rawDescData = file_rpc_article_proto_rawDesc
)

func file_rpc_article_proto_rawDescGZIP() []byte {
	file_rpc_article_proto_rawDescOnce.Do(func() {
		file_rpc_article_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_article_proto_rawDescData)
	})
	return file_rpc_article_proto_rawDescData
}

var file_rpc_article_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rpc_article_proto_goTypes = []interface{}{
	(*ArtsRequest)(nil),       // 0: rpc.ArtsRequest
	(*Art)(nil),               // 1: rpc.Art
	(*ArtsResponse)(nil),      // 2: rpc.ArtsResponse
	(*ArtRequest)(nil),        // 3: rpc.ArtRequest
	(*ArtResponse)(nil),       // 4: rpc.ArtResponse
	(*AddArtRequest)(nil),     // 5: rpc.AddArtRequest
	(*AddArtResponse)(nil),    // 6: rpc.AddArtResponse
	(*MyArtRequest)(nil),      // 7: rpc.MyArtRequest
	(*MyArtResponse)(nil),     // 8: rpc.MyArtResponse
	(*UpdateArtRequest)(nil),  // 9: rpc.UpdateArtRequest
	(*UpdateArtResponse)(nil), // 10: rpc.UpdateArtResponse
	(*DelArtRequest)(nil),     // 11: rpc.DelArtRequest
	(*DelArtResponse)(nil),    // 12: rpc.DelArtResponse
}
var file_rpc_article_proto_depIdxs = []int32{
	1,  // 0: rpc.ArtsResponse.Date:type_name -> rpc.Art
	1,  // 1: rpc.ArtResponse.Date:type_name -> rpc.Art
	1,  // 2: rpc.MyArtResponse.Date:type_name -> rpc.Art
	1,  // 3: rpc.UpdateArtResponse.Date:type_name -> rpc.Art
	1,  // 4: rpc.DelArtResponse.Date:type_name -> rpc.Art
	0,  // 5: rpc.Article.Articles:input_type -> rpc.ArtsRequest
	3,  // 6: rpc.Article.Article:input_type -> rpc.ArtRequest
	5,  // 7: rpc.Article.AddMyArticle:input_type -> rpc.AddArtRequest
	7,  // 8: rpc.Article.MyArticle:input_type -> rpc.MyArtRequest
	9,  // 9: rpc.Article.UpdateArticle:input_type -> rpc.UpdateArtRequest
	11, // 10: rpc.Article.DelArticle:input_type -> rpc.DelArtRequest
	2,  // 11: rpc.Article.Articles:output_type -> rpc.ArtsResponse
	4,  // 12: rpc.Article.Article:output_type -> rpc.ArtResponse
	6,  // 13: rpc.Article.AddMyArticle:output_type -> rpc.AddArtResponse
	8,  // 14: rpc.Article.MyArticle:output_type -> rpc.MyArtResponse
	10, // 15: rpc.Article.UpdateArticle:output_type -> rpc.UpdateArtResponse
	12, // 16: rpc.Article.DelArticle:output_type -> rpc.DelArtResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rpc_article_proto_init() }
func file_rpc_article_proto_init() {
	if File_rpc_article_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_article_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Art); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyArtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyArtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_article_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_article_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_article_proto_goTypes,
		DependencyIndexes: file_rpc_article_proto_depIdxs,
		MessageInfos:      file_rpc_article_proto_msgTypes,
	}.Build()
	File_rpc_article_proto = out.File
	file_rpc_article_proto_rawDesc = nil
	file_rpc_article_proto_goTypes = nil
	file_rpc_article_proto_depIdxs = nil
}
