// Code generated by goctl. DO NOT EDIT.
package types

type PeoResponse struct {
	Code   int64    `json:"code"`
	Msg    string `json:"msg"`
	Time   []int64  `json:"time"`
	People []int64  `json:"people"`
}

type JobResponse struct {
	Code   int64      `json:"code"`
	Msg    string   `json:"msg"`
	Job    []string `json:"job"`
	People []int64    `json:"people"`
}
