// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"user/rpc/internal/logic"
	"user/rpc/internal/svc"
	"user/rpc/rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *rpc.LoginRequest) (*rpc.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *rpc.RegisterRequest) (*rpc.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) MailSendCode(ctx context.Context, in *rpc.MailSendRequest) (*rpc.MailSendResponse, error) {
	l := logic.NewMailSendCodeLogic(ctx, s.svcCtx)
	return l.MailSendCode(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *rpc.UserInfoRequest) (*rpc.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) UserInsert(ctx context.Context, in *rpc.UserInsertRequest) (*rpc.UserInsertResponse, error) {
	l := logic.NewUserInsertLogic(ctx, s.svcCtx)
	return l.UserInsert(in)
}
