// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Company string `json:"company"`
	Brief   string `json:"brief"`
	Picture string `json:"picture"`
}

type CreateResponse struct {
	Id int64 `json:"id"`
}

type UpdateRequest struct {
	Id      int64  `json:"id"`
	Company string `json:"company,optional"`
	Brief   string `json:"brief"`
	Picture string `json:"picture"`
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id int64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id int64 `json:"id"`
}

type DetailResponse struct {
	Id      int64  `json:"id"`
	Company string `json:"company"`
	Number  int64  `json:"number"`
	Brief   string `json:"brief"`
	Picture string `json:"picture"`
}

type ListRequest struct {
}

type ListResponse struct {
	Id      int64  `json:"id"`
	Company string `json:"company"`
	Number  int64  `json:"number"`
	Brief   string `json:"brief"`
	Picture string `json:"picture"`
}

type RefreshRequest struct {
	Id int64 `json:"id"`
}

type RefreshResponse struct {
	Id      int64  `json:"id"`
	Company string `json:"company"`
	Number  int64  `json:"number"`
	Brief   string `json:"brief"`
	Picture string `json:"picture"`
}
