// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"
	"fmt"

	"user/rpc/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginRequest     = rpc.LoginRequest
	LoginResponse    = rpc.LoginResponse
	RegisterRequest  = rpc.RegisterRequest
	RegisterResponse = rpc.RegisterResponse
	UserInfoRequest  = rpc.UserInfoRequest
	UserInfoResponse = rpc.UserInfoResponse

	User interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := rpc.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := rpc.NewUserClient(m.cli.Conn())
	fmt.Println("rpc---")
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := rpc.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
