// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Account  string    `json:"account"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code	int	`json:"code"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Account  string `json:"Account"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInsertRequst struct {
	Name     string `json:"name"`
	Sex      string `json:"sex"`
	Age      int    `json:"age"`
	Phone    string `json:"phone"`
	Mail     string `json:"mail"`
	Identity string `json:"identity"`
	Need     string `json:"need"`
}

type UserInsertRespinse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UserInfoResponse struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Sex      string `json:"sex"`
	Age      int    `json:"age"`
	Phone    string `json:"phone"`
	Mail     string `json:"mail"`
	Identity string `json:"identity"`
	Need     string `json:"need"`
}
