// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: rpc/job.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerchJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=Sql,proto3" json:"Sql,omitempty"`
}

func (x *SerchJobRequest) Reset() {
	*x = SerchJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerchJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerchJobRequest) ProtoMessage() {}

func (x *SerchJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerchJobRequest.ProtoReflect.Descriptor instead.
func (*SerchJobRequest) Descriptor() ([]byte, []int) {
	return file_rpc_job_proto_rawDescGZIP(), []int{0}
}

func (x *SerchJobRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type SerchJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Date []*Job `protobuf:"bytes,3,rep,name=Date,proto3" json:"Date,omitempty"`
}

func (x *SerchJobResponse) Reset() {
	*x = SerchJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerchJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerchJobResponse) ProtoMessage() {}

func (x *SerchJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerchJobResponse.ProtoReflect.Descriptor instead.
func (*SerchJobResponse) Descriptor() ([]byte, []int) {
	return file_rpc_job_proto_rawDescGZIP(), []int{1}
}

func (x *SerchJobResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SerchJobResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SerchJobResponse) GetDate() []*Job {
	if x != nil {
		return x.Date
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CId         string `protobuf:"bytes,2,opt,name=CId,proto3" json:"CId,omitempty"`
	Company     string `protobuf:"bytes,3,opt,name=Company,proto3" json:"Company,omitempty"`
	Title       string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	JobCategory string `protobuf:"bytes,5,opt,name=JobCategory,proto3" json:"JobCategory,omitempty"`
	JobTypeName string `protobuf:"bytes,6,opt,name=JobTypeName,proto3" json:"JobTypeName,omitempty"`
	JobDetail   string `protobuf:"bytes,7,opt,name=JobDetail,proto3" json:"JobDetail,omitempty"`
	JobLocation string `protobuf:"bytes,8,opt,name=JobLocation,proto3" json:"JobLocation,omitempty"`
	PushTime    string `protobuf:"bytes,9,opt,name=push_time,json=pushTime,proto3" json:"push_time,omitempty"`
	FetchTime   string `protobuf:"bytes,10,opt,name=fetch_time,json=fetchTime,proto3" json:"fetch_time,omitempty"`
}

func (x *Job) Reset() {
	*x = Job{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_rpc_job_proto_rawDescGZIP(), []int{2}
}

func (x *Job) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Job) GetCId() string {
	if x != nil {
		return x.CId
	}
	return ""
}

func (x *Job) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetJobCategory() string {
	if x != nil {
		return x.JobCategory
	}
	return ""
}

func (x *Job) GetJobTypeName() string {
	if x != nil {
		return x.JobTypeName
	}
	return ""
}

func (x *Job) GetJobDetail() string {
	if x != nil {
		return x.JobDetail
	}
	return ""
}

func (x *Job) GetJobLocation() string {
	if x != nil {
		return x.JobLocation
	}
	return ""
}

func (x *Job) GetPushTime() string {
	if x != nil {
		return x.PushTime
	}
	return ""
}

func (x *Job) GetFetchTime() string {
	if x != nil {
		return x.FetchTime
	}
	return ""
}

var File_rpc_job_proto protoreflect.FileDescriptor

var file_rpc_job_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x70, 0x63, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x72, 0x70, 0x63, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x71, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x71, 0x6c, 0x22, 0x56, 0x0a, 0x10, 0x53, 0x65, 0x72,
	0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x22, 0x97, 0x02, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4a,
	0x6f, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x4a, 0x6f, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x4a, 0x6f, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4a, 0x6f, 0x62, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x4a, 0x6f, 0x62, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x4a, 0x6f, 0x62, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a,
	0x0b, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x4a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x65, 0x74, 0x63, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x3c, 0x0a, 0x04, 0x53,
	0x4a, 0x6f, 0x62, 0x12, 0x34, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x63, 0x68, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x63, 0x68, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_job_proto_rawDescOnce sync.Once
	file_rpc_job_proto_rawDescData = file_rpc_job_proto_rawDesc
)

func file_rpc_job_proto_rawDescGZIP() []byte {
	file_rpc_job_proto_rawDescOnce.Do(func() {
		file_rpc_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_job_proto_rawDescData)
	})
	return file_rpc_job_proto_rawDescData
}

var file_rpc_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_job_proto_goTypes = []interface{}{
	(*SerchJobRequest)(nil),  // 0: rpc.SerchJobRequest
	(*SerchJobResponse)(nil), // 1: rpc.SerchJobResponse
	(*Job)(nil),              // 2: rpc.Job
}
var file_rpc_job_proto_depIdxs = []int32{
	2, // 0: rpc.SerchJobResponse.Date:type_name -> rpc.Job
	0, // 1: rpc.SJob.Login:input_type -> rpc.SerchJobRequest
	1, // 2: rpc.SJob.Login:output_type -> rpc.SerchJobResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_job_proto_init() }
func file_rpc_job_proto_init() {
	if File_rpc_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerchJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerchJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Job); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_job_proto_goTypes,
		DependencyIndexes: file_rpc_job_proto_depIdxs,
		MessageInfos:      file_rpc_job_proto_msgTypes,
	}.Build()
	File_rpc_job_proto = out.File
	file_rpc_job_proto_rawDesc = nil
	file_rpc_job_proto_goTypes = nil
	file_rpc_job_proto_depIdxs = nil
}
