// Code generated by goctl. DO NOT EDIT.
package types

type Articles struct {
	Uuid    int64  `json:"uuid"`
	UserId  int64  `json:"user_id"`
	Name    string `json:"name"`
	Info    string `json:"info"`
	Tag     string `json:"tag"`
	Time    int64  `json:"time"`
	LikeSum int64  `json:"like_sum"`
}

type ArtsRequest struct {
	NextID   int64 `json:"next_id"`
	PageSize int64 `json:"page_size"`
}

type ArtsResponse struct {
	Code int64      `json:"code"`
	Date []Articles `json:"date"`
}

type ArtRequest struct {
	Name string `json:"name"`
}

type ArtResponse struct {
	Code int64      `json:"code"`
	Msg  string     `json:"msg"`
	Date []Articles `json:"date"`
}

type ARequest struct {
	Uuid int64 `json:"uuid"`
}

type AResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Date Articles `json:"date"`
}

type AddArtRequest struct {
	Name string `json:"name"`
	Info string `json:"info"`
	Tag  string `json:"tag"`
	Time int64  `json:"time"`
}

type AddArtResponse struct {
	Code int64  `json:"code"`
	Msg  string `json:"msg"`
}

type MyArtResponse struct {
	Code int64      `json:"code"`
	Msg  string     `json:"msg"`
	Date []Articles `json:"date"`
}

type UpdateArtRequest struct {
	ArtId int64  `json:"art_id"`
	Name  string `json:"name"`
	Info  string `json:"info"`
	Tag   string `json:"tag"`
	Time  int64  `json:"time"`
}

type UpdateArtResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Date Articles `json:"date"`
}

type DelArtRequest struct {
	ArtId int64 `json:"art_id"`
}

type DelArtResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Date Articles `json:"date"`
}

type LikeRequest struct {
	ArtId int64 `json:"art_id"`
	Sum   int64 `json:"sum"`
}

type LikeResponse struct {
	Code int64    `json:"code"`
	Msg  string   `json:"msg"`
	Date Articles `json:"date"`
}
